name: CI with Docker Compose

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    steps:
      #step 1
      - name: Checkout repoistory
        uses: actions/checkout@v3

      #Step 2: set up docker compose
      - name: Start services with Docker Compose
        run: docker compose up --build --abort-on-container-exit

      #Step 3: Tear down services
      - name: Stop and clean up Docket Compose
        if: always()
        run: docker compose down
